### ISSUE TITLE
Impossible to run test

### ISSUE THREAD

**Issue by eneiluj** [kamimrcht/ELECTOR#1]
Hi there,

After having difficulties to run ELECTOR on my data, i decided to check if i was able to run it with provided test data and i have the same problem. Here is what i do : 
```bash
git clone --recursive https://github.com/kamimrcht/ELECTOR
cd ELECTOR
./install.sh # which runs correctly
# fastq-to-fasta.py is provided by "khmer" package in Ubuntu/Debian repositories
fastq-to-fasta.py example/Simlord/simulatedReads.fastq > example/Simlord/simulatedReads.fasta
python3 elector.py -perfect example/example_reference.fasta -corrected example/Simlord/correctedReads.fasta -uncorrected example/Simlord/simulatedReads.fasta
```

and here is the output : 
```
- Mean that a large amount of nuc has been handled: 100000000
-rm: impossible de supprimer 'swag*': Aucun fichier ou dossier de ce type

mv: impossible d'évaluer 'merger': Aucun fichier ou dossier de ce type
Traceback (most recent call last):
  File "elector.py", line 154, in <module>
    main()
  File "elector.py", line 125, in main
    precision, recall, correctBaseRate, meanMissing, smallReads, percentGCRef, percentGCCorr, numberSplit, meanMissing, indelsubsUncorr, indelsubsCorr  = computeStats.outputRecallPrecision(sortedCorrectedFileName, outputDirPath, logFile, 0, 0, soft)
  File "/tmp/ELECTOR/computeStats.py", line 99, in outputRecallPrecision
    precision, recall, corBasesRate, missingSize, smallReadNumber, GCRateRef, GCRateCorr, indelsubsUncorr, indelsubsCorr = computeMetrics(outDir + "/msa.fa", outProfile, outMetrics, correctedFileName)
  File "/tmp/ELECTOR/computeStats.py", line 222, in computeMetrics
    msa = open(fileName, 'r')
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/ELECTOR/msa.fa'
```

Am i doing something wrong ? Is this a bug ?

I tried to dig a little bit in the code but i guess if it's a bug, you'll find it faster than i would.

**Comment by eneiluj** [comment]
I tried again with my data and it went well. The problem was the `-corrector LoRDEC`. Changing it to `-corrector lordec` made the problem go away.

As an improvement, -corrector value could be converted to lowercase and there could be a check and an explicit error message when no corrector is selected or the selected one does not exist.

**Comment by morispi** [comment]
Hi,

ELECTOR is still under development, so it is more than likely that some more bugs, and other things such as the corrector having to be supplied in lowercase are still around. We are working on it.

Thanks for your interest in our tool.

Pierre
