### ISSUE TITLE
Couldn't evaluate CONSENT corrector. (Error in alignment.getPOA)

### ISSUE THREAD

**Issue by Shen-Jing** [kamimrcht/ELECTOR#9]
Hello!
Sorry to bother you.

### Environment

- Python: 3.8
- Corrector: CONSENT
- Data:
(That's too big to be upload.)

### Executed command

```bash
python3 -m elector -reference /mnt/d/Backup_Sync/Programming/ELECTOR_v1.0.4/reproduce_manuscript_results/references/Ecoli.fasta -uncorrected /root/data/ecoli_d70 -corrected /root/data/CONSENT-corrected.fasta -corrector consent -simulator simlord -output CONSENT_evaluation
```

- Output:

```
- Means that a large amount of reads has been handled: 10000
/mnt/d/Backup_Sync/Programming/ELECTOR_v1.0.4/elector/../bin/masterSplitter CONSENT_eval/reference_sorted_duplicated_consent.fa CONSENT_eval/uncorrected_sorted_duplicated_consent.fa CONSENT_eval/corrected_sorted_by_consent.fa CONSENT_e
val/out1 CONSENT_eval/out2 CONSENT_eval/out3 7 200 10000 0.1 CONSENT_eval
10000 200 50
```

And half an hour later, no change (output).

I pressed Ctrl C and got this error:

```bash
^CTraceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 848, in next
    item = self._items.popleft()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/mnt/d/Backup_Sync/Programming/ELECTOR_v1.0.4/elector/__main__.py", line 168, in <module>
    main()
  File "/mnt/d/Backup_Sync/Programming/ELECTOR_v1.0.4/elector/__main__.py", line 141, in main
    smallReads, wronglyCorReads = alignment.getPOA(sortedCorrectedFileName, sortedRefFileName, sortedUncoFileName, args.threads, outputDirPath, size_corrected_read_threshold, soft)
  File "/mnt/d/Backup_Sync/Programming/ELECTOR_v1.0.4/elector/alignment.py", line 118, in getPOA
    for i in pool.imap_unordered(fpoa, range(200)):
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 853, in next
    self._cond.wait(timeout)
  File "/usr/lib/python3.8/threading.py", line 302, in wait
    waiter.acquire()
KeyboardInterrupt
```

**Comment by Shen-Jing** [comment]
Sorry.

Because I have encountered similar stuck situation, I thought this time too.

But after hours later, the output starts to change.
Finally, it successfully finished.

Apologize for my impatience. 😥
